Repository sliit-foss/sliitfoss, pull requests merged in 2020-12, with the labels that each got.

#47 Navbar Toggle Added
  README.md
  src/app/app.module.ts
  src/app/components/common/navbar/navbar.component.html
  src/index.html
Labels: bug

#55 Events Carousel Added
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/home/home.component.html
  src/app/components/member/member.component.css
  src/app/components/member/member.component.html
  src/app/components/past-events/past-events.component.css
  src/app/components/past-events/past-events.component.html
  src/app/components/past-events/past-events.component.spec.ts
  src/app/components/past-events/past-events.component.ts
  src/app/components/what-we-do/what-we-do.component.html
  src/app/components/what-we-do/what-we-do.component.ts
  src/assets/data/events.json
  tsconfig.json
Labels: bug, enhancement

#61 Contact Us Page Structure Created
  src/app/components/common/navbar/navbar.component.html
  src/app/components/contact/contact.component.css
  src/app/components/contact/contact.component.html
Labels: enhancement
