Repository sliit-foss/sliitfoss, pull requests merged in 2020-10, with the labels that each got.

#9 Site NavBar & Footer Added
  package-lock.json
  package.json
  src/app/about/about.component.css
  src/app/about/about.component.html
  src/app/about/about.component.spec.ts
  src/app/about/about.component.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/contact/contact.component.css
  src/app/contact/contact.component.html
  src/app/contact/contact.component.spec.ts
  src/app/contact/contact.component.ts
  src/app/footer/footer.component.css
  src/app/footer/footer.component.html
  src/app/footer/footer.component.spec.ts
  src/app/footer/footer.component.ts
  src/app/navbar/navbar.component.css
  src/app/navbar/navbar.component.html
  src/app/navbar/navbar.component.spec.ts
  src/app/navbar/navbar.component.ts
  src/index.html
  src/styles.css
Labels: hacktoberfest-accepted

#17 Feature/home
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/footer/footer.component.css
  src/app/footer/footer.component.html
  src/app/home/home.component.css
  src/app/home/home.component.html
  src/app/home/home.component.spec.ts
  src/app/home/home.component.ts
  src/app/member/member.component.css
  src/app/member/member.component.html
  src/app/member/member.component.spec.ts
  src/app/member/member.component.ts
  src/app/navbar/navbar.component.css
  src/app/navbar/navbar.component.html
  src/assets/img/img-member.svg
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#20 Hot Fixes
  .prettierignore
  .prettierrc
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/about/about.component.css
  src/app/components/about/about.component.html
  src/app/components/about/about.component.spec.ts
  src/app/components/about/about.component.ts
  src/app/components/common/footer/footer.component.css
  src/app/components/common/footer/footer.component.html
  src/app/components/common/footer/footer.component.spec.ts
  src/app/components/common/footer/footer.component.ts
  src/app/components/common/navbar/navbar.component.css
  src/app/components/common/navbar/navbar.component.html
  src/app/components/common/navbar/navbar.component.spec.ts
  src/app/components/common/navbar/navbar.component.ts
  src/app/components/contact/contact.component.css
  src/app/components/contact/contact.component.html
  src/app/components/contact/contact.component.spec.ts
  src/app/components/contact/contact.component.ts
  src/app/components/home/home.component.css
  src/app/components/home/home.component.html
  src/app/components/home/home.component.spec.ts
  src/app/components/home/home.component.ts
  src/app/components/member/member.component.css
  src/app/components/member/member.component.html
  src/app/components/member/member.component.spec.ts
  src/app/components/member/member.component.ts
  tslint.json
  yarn.lock
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#21 Create node.js.yml
  .github/workflows/node.js.yml
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#23 Brand Logo Added
  src/assets/img/logo-dark.png
  src/assets/img/logo-light.png
Labels: hacktoberfest-accepted

#22 Feature/we do
  src/app/app.module.ts
  src/app/components/common/footer/footer.component.css
  src/app/components/home/home.component.html
  src/app/components/member/member.component.html
  src/app/components/we-do/we-do.component.css
  src/app/components/we-do/we-do.component.html
  src/app/components/we-do/we-do.component.spec.ts
  src/app/components/we-do/we-do.component.ts
  src/assets/img/img-we-do.svg
  src/index.html
Labels: bug, hacktoberfest-accepted, help wanted

#24 Feature/ceo
  src/app/app.module.ts
  src/app/components/ceo/ceo.component.css
  src/app/components/ceo/ceo.component.html
  src/app/components/ceo/ceo.component.spec.ts
  src/app/components/ceo/ceo.component.ts
  src/app/components/home/home.component.html
  src/app/components/we-do/we-do.component.html
  src/assets/img/img-Mr-Fluter.jpg
Labels: bug, help wanted

#29 Alignment Improved
  src/app/components/member/member.component.html
  src/app/components/we-do/we-do.component.css
  src/app/components/we-do/we-do.component.html
Labels: hacktoberfest, hacktoberfest-accepted

#33 fixed #15
  src/app/components/common/navbar/navbar.component.css
  src/app/components/common/navbar/navbar.component.html
Labels: hacktoberfest, hacktoberfest-accepted
