Repository sliit-foss/sliitfoss, pull requests merged in 2021-01, with the labels that each got.

#129 Firebase CD Status Badge Added to README.md
  README.md
Labels: good to merge

#139 change favicon , contact us image and fonts
  src/app/components/about/about.component.css
  src/app/components/about/about.component.html
  src/app/components/board/board.component.css
  src/app/components/contact/contact.component.css
  src/app/components/contact/contact.component.html
  src/app/components/events/events.component.css
  src/app/components/latest-blog-posts/latest-blog-posts.component.css
  src/app/components/member/member.component.css
  src/app/components/past-events/past-events.component.css
  src/assets/img/contactus.png
  src/favicon.ico
  src/styles.css
Labels: changes requested

#143 Added Hyperlinks to Brand Assets and Contribution Guideline
  src/app/components/common/footer/footer.component.html
Labels: changes requested, critical, enhancement

#149 White background removed from Coding vector
  src/app/components/member/member.component.html
  src/assets/img/coding-vector.jpg
  src/assets/img/coding-vector.png
Labels: good to merge
