Repository sliit-foss/sliitfoss, pull requests merged in 2021-02, with the labels that each got.

#185 Fixed Footer Content
  src/app/components/common/footer/footer.component.html
Labels: good to merge, women-in-foss

#186 Added Footer Links 😋
  src/app/components/common/footer/footer.component.html
Labels: good to merge

#198 Fixed Podcast Content
  src/app/components/home/podcastsection/podcastsection.component.html
Labels: good to merge

#202 Changes on Footer
  src/app/components/common/footer/footer.component.html
Labels: review needed
