Repository sliit-foss/sliitfoss, pull requests merged in 2021-05, with the labels that each got.

#225 Common style classes
  src/app/components/about/about.component.css
  src/app/components/about/about.component.html
  src/app/components/board/board.component.css
  src/app/components/board/board.component.html
  src/app/components/events/events.component.html
  src/styles.css
Labels: critical, enhancement

#236 Board Data | UI Fixes
  package-lock.json
  src/app/app.component.css
  src/app/app.component.html
  src/app/components/about/about.component.css
  src/app/components/about/about.component.html
  src/app/components/about/about.component.ts
  src/app/components/blog/blog.component.css
  src/app/components/blog/blog.component.html
  src/app/components/board/board.component.html
  src/app/components/board/board.component.ts
  src/app/components/contact/contact.component.css
  src/app/components/contact/contact.component.html
  src/app/components/contact/contact.component.ts
  src/app/components/events/events.component.css
  src/app/components/events/events.component.html
  src/app/components/events/events.component.ts
  src/app/components/home/podcastsection/podcastsection.component.css
  src/app/components/home/podcastsection/podcastsection.component.html
  src/app/components/home/podcastsection/podcastsection.component.ts
  src/app/components/latest-blog-posts/latest-blog-posts.component.html
  src/app/components/member/member.component.css
  src/app/components/member/member.component.html
  src/app/components/member/member.component.ts
  src/app/components/past-events/past-events.component.css
  src/app/components/past-events/past-events.component.html
  src/app/components/webinars/webinars.component.ts
  src/assets/data/board.json
  src/assets/data/webinars.json
  src/assets/img/events/building_communities.jpg
  src/assets/img/events/github-community.jpg
  src/assets/js/tilt.jquery.min.js
  src/index.html
  src/styles.css
Labels: enhancement

#242 Did some UI changes
  src/app/components/about/about.component.html
  src/app/components/common/footer/footer.component.html
  src/app/components/events/events.component.css
  src/app/components/events/events.component.html
  src/app/components/past-events/past-events.component.ts
  src/app/components/webinars/webinars.component.css
  src/app/components/webinars/webinars.component.html
  src/app/components/webinars/webinars.component.ts
  src/styles.css
Labels: good to merge

#250 Fixes #249
  src/app/components/board/board.component.html
  src/app/components/board/board.component.ts
  src/assets/data/board.json
  src/robots.txt
Labels: bug, enhancement

#251 PWA: Cache Policy Added with Service Worker
  angular.json
  ngsw-config.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/blog/blog.component.ts
  src/app/components/contact/contact.component.ts
  src/assets/icons/icon-128x128.png
  src/assets/icons/icon-144x144.png
  src/assets/icons/icon-152x152.png
  src/assets/icons/icon-192x192.png
  src/assets/icons/icon-384x384.png
  src/assets/icons/icon-512x512.png
  src/assets/icons/icon-72x72.png
  src/assets/icons/icon-96x96.png
  src/index.html
  src/manifest.webmanifest
Labels: PWA, enhancement, review needed

#264 Feature/contact us
  package.json
  src/app/components/contact/contact.component.css
  src/app/components/contact/contact.component.html
  src/app/components/contact/contact.component.ts
  src/environments/environment.prod.ts
  yarn.lock
Labels: WIP

#265 Avatar Vector Added
  package-lock.json
  src/app/components/about/about.component.css
  src/app/components/common/navbar/navbar.component.css
  src/app/components/common/navbar/navbar.component.html
  src/app/components/member/member.component.css
  src/assets/data/board.json
  src/assets/img/avatar.png
  src/styles.css
Labels: enhancement
